version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: test_sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"