version: "3.8"

services:
  sqlserver:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: sqlcore_sqlserver
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"
    # No volume needed since we copied setup.sql into the image
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Password -i /tmp/setup.sql &&
      wait
      "