name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "YourStrong@Password"
          ACCEPT_EULA: "Y"
        options: --platform linux/amd64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install
        env:
          PYTHONPATH: .

      # Install SQL Server command-line tools (sqlcmd)
      - name: Install SQL Server Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https gnupg2
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Wait for SQL Server
        run: |
          for i in {1..30}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P "YourStrong@Password" -Q "SELECT 1" && break || sleep 2
          done

      - name: Run Database Setup
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P "YourStrong@Password" -i docker/setup.sql

      - name: Run Tests
        run: poetry run pytest
        env:
          PYTHONPATH: .