name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest  # Use the official SQL Server image
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "YourStrong@Password"
          ACCEPT_EULA: "Y"
        options: --platform linux/amd64  # Ensure compatibility

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          poetry install
        env:
          PYTHONPATH: .

      # Step 5: Wait for Database to Start
      - name: Wait for SQL Server
        run: |
          for i in {1..30}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P "YourStrong@Password" -Q "SELECT 1" && break || sleep 2
          done

      # Step 6: Run Tests
      - name: Run Tests
        run: |
          poetry run pytest
        env:
          PYTHONPATH: .